/* This file was generated by the "SVNRevision" utility
 * You should not modify it manually, as it may be re-generated.
 */

package client.editor.svn;

public interface SvnRevision {
    int SVN_REV = 5258;
    String SVN_REV_STR = "5258";
    String SVN_REV_DATE = "2020-04-18";
    String SVN_REV_DATE_TIME = "2020-04-18 15:12:12";
    long SVN_REV_STAMP = 1587211932806L;
}
