/* This file was generated by the "SVNRevision" utility
 * You should not modify it manually, as it may be re-generated.
 */

package client.reporter.svn;

public interface SvnRevision {
    int SVN_REV = 5220;
    String SVN_REV_STR = "5220";
    String SVN_REV_DATE = "2020-03-25";
    String SVN_REV_DATE_TIME = "2020-03-25 11:45:06";
    long SVN_REV_STAMP = 1585125906517L;
}
